# Generated by Django 3.0.4 on 2020-07-08 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('religion', models.CharField(max_length=100, null=True)),
                ('denomination', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('number_of_children', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='nunny',
            name='category',
            field=models.CharField(choices=[('LiveIn', 'LiveIn'), ('Dayburg', 'Dayburg'), ('Emmergency', 'Emergency')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nunny',
            name='pay_range',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Queued for allocation', 'Queued for allocation'), ('Allocated', 'Allocated')], max_length=100, null=True)),
                ('houseowner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.HouseOwner')),
                ('nunny', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Nunny')),
            ],
        ),
    ]
