# Generated by Django 3.0.4 on 2020-07-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200712_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='nunny',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
